apiVersion: v1

kind: PersistentVolumeClaim

metadata:

     name: golang-mathapp-pvc

     namespace: mohamedhadizaira

spec:

 accessModes:

 - ReadWriteOnce

 resources:

   requests:

    storage: 1Gi

  storageClassName: gp2

  volumeMode: Filesystem